# Generated by Django 4.0 on 2021-12-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0002_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='announcement',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
