# Generated by Django 4.0 on 2021-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0003_update_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='preffered',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
