# Generated by Django 4.0 on 2021-12-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0007_alter_scores_correct_alter_scores_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option1',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option2',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option3',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option4',
            new_name='D',
        ),
    ]
