# Generated by Django 4.0 on 2021-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0009_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dates',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dates',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
