# Generated by Django 4.0 on 2021-12-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0010_dates_end_dates_start_alter_dates_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='preffered',
            new_name='course',
        ),
    ]
