# Generated by Django 4.0 on 2021-12-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0011_rename_preffered_questions_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
