# Generated by Django 4.0 on 2022-01-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0012_newsform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsform',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EDU.questions')),
            ],
        ),
    ]
