# Generated by Django 4.0 on 2022-01-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('EDU', '0014_class_department_major_lesson_class_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=' ', max_length=100, null=True)),
                ('lname', models.CharField(default=' ', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('student_id', models.CharField(default=' ', max_length=15, null=True)),
                ('classes', models.ManyToManyField(to='EDU.Class')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EDU.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
