# Generated by Django 4.0 on 2022-01-01 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0015_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='related',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quit', models.CharField(max_length=100)),
                ('relate_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EDU.courses')),
            ],
        ),
    ]
