# Generated by Django 4.0 on 2022-01-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0016_remove_courses_related_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='major',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='relate_class',
        ),
        migrations.RemoveField(
            model_name='major',
            name='department',
        ),
        migrations.DeleteModel(
            name='Newsform',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quit',
        ),
        migrations.AddField(
            model_name='question',
            name='A',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='B',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='C',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='D',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
