# Generated by Django 4.0 on 2022-01-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0017_remove_class_major_remove_lesson_relate_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=120)),
                ('courseDescription', models.TextField()),
                ('courseCost', models.CharField(max_length=120)),
                ('courseDuration', models.CharField(max_length=120)),
                ('courseCategory', models.CharField(max_length=120)),
                ('courseModeOfDelivery', models.CharField(max_length=120)),
                ('courseSkillLevel', models.CharField(max_length=120)),
                ('coursePrerequisite', models.CharField(max_length=120)),
                ('updated', models.DateField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
