# Generated by Django 4.0 on 2022-02-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0019_everything_student_teacher_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolled_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
