# Generated by Django 4.0 on 2022-02-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('EDU', '0020_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled_courses',
            name='name',
        ),
        migrations.AddField(
            model_name='enrolled_courses',
            name='everything',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EDU.everything'),
        ),
        migrations.AddField(
            model_name='everything',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='everything',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
