# Generated by Django 4.0 on 2022-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0022_remove_everything_user_everything_classcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='everything',
            name='lecturer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
