# Generated by Django 4.0 on 2022-02-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0024_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
