# Generated by Django 4.0 on 2022-02-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0028_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
