# Generated by Django 4.0 on 2022-02-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0029_profile_email_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='everything',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
