# Generated by Django 4.0 on 2022-02-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('EDU', '0031_alter_enrolled_courses_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrolled_Courses',
            new_name='Enrolled',
        ),
    ]
