# Generated by Django 4.0 on 2022-02-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0039_alter_everything_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everything',
            name='user',
        ),
    ]
