# Generated by Django 4.0 on 2022-02-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0043_alter_enrolled_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='everything',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='user',
        ),
        migrations.AddField(
            model_name='everything',
            name='enrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EDU.enrolled'),
        ),
    ]
