# Generated by Django 4.0 on 2022-02-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0044_remove_enrolled_everything_remove_everything_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='user',
        ),
    ]
