# Generated by Django 4.0 on 2022-02-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0045_remove_enrolled_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everything',
            name='enrolled',
        ),
        migrations.DeleteModel(
            name='Enrolled',
        ),
    ]
