# Generated by Django 4.0 on 2022-02-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('EDU', '0048_remove_everything_users_everything_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everything',
            name='user',
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('everything', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EDU.everything')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
