# Generated by Django 4.0 on 2022-02-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0050_remove_enroll_everything_everything_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('relate_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EDU.class')),
            ],
        ),
    ]
