# Generated by Django 4.0 on 2022-03-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EDU', '0055_remove_lesson_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
